"""added username

Revision ID: 921b3b3e2ee3
Revises: 8be848b917dd
Create Date: 2024-04-18 15:14:25.014406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '921b3b3e2ee3'
down_revision = '8be848b917dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=20), nullable=False))
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
